name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: self-hosted

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      GITHUB_USER: AbhinavVumonic
      CLUSTER_CONTEXT: gke_letters-297411_europe-west3_vm-kcl-letters-data-pull-p-euwe3-gke
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config
    
    - name: Install FluxCD Toolkit
      run: |
        wget -O install_fluxcd.sh https://toolkit.fluxcd.io/install.sh
        sudo bash install_fluxcd.sh

    - name: Install GKE authentication plugin
      run: |
        PLUGIN_VERSION="0.2.1"
        wget -O gke-gcloud-auth-plugin.tar.gz https://github.com/GoogleCloudPlatform/cloud-providers-gcp/releases/download/gke-auth-plugin-v${PLUGIN_VERSION}/gke-cloud-auth-plugin-linux-amd64-v${PLUGIN_VERSION}.tar.gz
        tar -zxvf gke-gcloud-auth-plugin.tar.gz
        chmod +x gke-cloud-auth-plugin-linux-amd64-v${PLUGIN_VERSION}/gke-gcloud-auth-plugin
        sudo mv gke-cloud-auth-plugin-linux-amd64-v${PLUGIN_VERSION}/gke-gcloud-auth-plugin /usr/local/bin/
      
    - name: Configure Flux
      run: |
        flux bootstrap --components-extra=image-reflector-controller,image-automation-controller github \
          --owner=${{ github.repository_owner }} \
          --repository=${{ github.event.repository.name }} \
          --branch=main \
          --path=./bootstrap \
          --read-write-key \
          --personal \
          --kubeconfig=$HOME/.kube/config \
          --context=${{ env.CLUSTER_CONTEXT }}
          
    - name: Commit and Push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add -A
        git commit -m "Update manifests"
        git push
