name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install FluxCD Toolkit
      run: |
        wget -O install_fluxcd.sh https://toolkit.fluxcd.io/install.sh
        sudo bash install_fluxcd.sh
      
    - name: Configure Flux
      run: |
        flux bootstrap --components-extra=image-reflector-controller,image-automation-controller github \
          --owner=${{ github.repository_owner }} \
          --repository=${{ github.event.repository.name }} \
          --branch=main \
          --path=./bootstrap \
          --read-write-key \
          --personal
          
    - name: Configure Flux
      run: |
        flux bootstrap --components-extra=image-reflector-controller,image-automation-controller github \
          --owner=${{ github.repository_owner }} \
          --repository=${{ github.event.repository.name }} \
          --branch=main \
          --path=./bootstrap \
          --read-write-key \
          --token=${{ secrets.GH_TOKEN }}
          
    - name: Commit and Push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add -A
        git commit -m "Update manifests"
        git push
